### ISSUE TITLE
URLError when using zap2epg.py on Synology NAS DSM 6.1

### ISSUE THREAD

**Issue by kianrafiee** [edit4ever/script.module.zap2epg#3]
Here is the log:

2018/01/28 15:40:35 Exception: main
Traceback (most recent call last):
  File "zap2epg.py", line 718, in mainRun
    tvhMatchGet()
  File "zap2epg.py", line 115, in tvhMatchGet
    response = urllib2.urlopen(channels_url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] Connection refused>

**Comment by kianrafiee** [comment]
Nevermind, had to turn tvhmatch to off! :)
