### ISSUE TITLE
Authentication issue with zap2epg and tvheadend 4.3

### ISSUE THREAD

**Issue by minnixtx** [edit4ever/script.module.zap2epg#32]
Currently running libreelec 9.95.2 with kodi 19.0 on a raspberry pi 4 4GB. Using zap2epg 2.0.2. zap2epg would not install at first until I installed the DVB tools addon. Then it installed from zip and I was able to fill in the settings and enable it in tvheadend epg grabber modules. tvheadend 4.3 is what I'm running btw. When I click on zap2epg within kodi it gives me "zap2epg error check log for information" but I don't know where the log is kept. I've ssh into the machine and looked around but see no log file. If you can point me to the way I can post the log here. Thanks.

**Comment by minnixtx** [comment]
Ok I was looking for a specific zap2epg log file but didn't think to look in kodi.log. This seems to be the relevant part:

'2021-05-08 14:20:42.203 T:1219    DEBUG <general>: CGUIMediaWindow::GetDirectory (plugin://script.module.zap2epg/)
2021-05-08 14:20:42.203 T:1219    DEBUG <general>:   ParentPath = [plugin://script.module.zap2epg/]
2021-05-08 14:20:42.203 T:1448    DEBUG <general>: Thread waiting start, auto delete: false
2021-05-08 14:20:42.205 T:1331    DEBUG <general>: CAddonDatabase::SetLastUsed[script.module.zap2epg] took 2 ms
2021-05-08 14:20:42.205 T:1448    DEBUG <general>: StartScript - calling plugin zap2epg('plugin://script.module.zap2epg/','1','','resume:false')
2021-05-08 14:20:42.205 T:1449    DEBUG <general>: Thread LanguageInvoker start, auto delete: false
2021-05-08 14:20:42.206 T:1449     INFO <general>: initializing python engine.
2021-05-08 14:20:42.206 T:1449    DEBUG <general>: CPythonInvoker(2, /storage/.kodi/addons/script.module.zap2epg/default.py): start processing
2021-05-08 14:20:42.237 T:1449    DEBUG <general>: -->Python Interpreter Initialized<--
2021-05-08 14:20:42.237 T:1449    DEBUG <general>:

2021-05-08 14:20:42.237 T:1449    DEBUG <general>: CPythonInvoker(2, /storage/.kodi/addons/script.module.zap2epg/default.py): the source file to load is "/storage/.kodi/addons/script.module.zap2epg/default.py"
2021-05-08 14:20:42.237 T:1449    DEBUG <general>: CPythonInvoker(2, /storage/.kodi/addons/script.module.zap2epg/default.py): setting the Python path to /storage/.kodi/addons/script.module.zap2epg:/storage/.kodi/addons/script.module.cert>
2021-05-08 14:20:42.238 T:1449    DEBUG <general>: CPythonInvoker(2, /storage/.kodi/addons/script.module.zap2epg/default.py): entering source directory /storage/.kodi/addons/script.module.zap2epg
2021-05-08 14:20:42.238 T:1449    DEBUG <general>: CPythonInvoker(2, /storage/.kodi/addons/script.module.zap2epg/default.py): instantiating addon using automatically obtained id of "script.module.zap2epg" dependent on version 3.0.0 of th>
2021-05-08 14:20:42.304 T:1219    DEBUG <general>: ------ Window Init (DialogBusy.xml) ------
2021-05-08 14:20:43.055 T:1449  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-05-08 14:20:43.055 T:1449    DEBUG <CAddonSettings[script.module.zap2epg]>: trying to load setting definitions from old format...
2021-05-08 14:20:43.108 T:1449     INFO <general>: Skipped 8 duplicate messages..
2021-05-08 14:20:43.108 T:1449    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'TypeError'>
                                                   Error Contents: function takes at most 2 arguments (4 given)
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.zap2epg/default.py", line 79, in <module>
                                                       check_status = check_load.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 943, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://minnix:in-ruins64@127.0.0.1:9981/api/status/connections

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.zap2epg/default.py", line 81, in <module>
                                                       dialog.ok("Tvheadend Access Error!", str(err), "", "Please check your username/password in settings.")
                                                   TypeError: function takes at most 2 arguments (4 given)
                                                   -->End of Python script error report<--

2021-05-08 14:20:43.108 T:1449    DEBUG <general>: onExecutionDone(2, /storage/.kodi/addons/script.module.zap2epg/default.py)
2021-05-08 14:20:43.108 T:1449    DEBUG <general>: onExecutionDone(2, /storage/.kodi/addons/script.module.zap2epg/default.py)
2021-05-08 14:20:43.137 T:1219    DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
2021-05-08 14:20:43.153 T:1449    DEBUG <general>: .
2021-05-08 14:20:43.280 T:1449     INFO <general>: Skipped 2 duplicate messages..
2021-05-08 14:20:43.280 T:1449     INFO <general>: Python interpreter stopped
2021-05-08 14:20:43.280 T:1449    DEBUG <general>: Thread LanguageInvoker 2493510304 terminating
2021-05-08 14:20:43.290 T:1448    ERROR <general>: GetDirectory - Error getting plugin://script.module.zap2epg/
2021-05-08 14:20:43.290 T:1448    DEBUG <general>: Thread waiting 2503631520 terminating
2021-05-08 14:20:43.303 T:1219    DEBUG <general>: ------ Window Deinit (DialogBusy.xml) ------
2021-05-08 14:20:43.303 T:1219    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://script.module.zap2epg/) failed
2021-05-08 14:20:43.303 T:1219    DEBUG <general>: CGUIMediaWindow::GetDirectory ()
2021-05-08 14:20:43.303 T:1219    DEBUG <general>:   ParentPath = [plugin://script.module.zap2epg/]
2021-05-08 14:20:43.305 T:1451    DEBUG <general>: Thread waiting start, auto delete: false
2021-05-08 14:20:43.305 T:1451    DEBUG <general>: Thread waiting 2503631520 terminating
2021-05-08 14:20:43.327 T:1452    DEBUG <general>: Thread BackgroundLoader start, auto delete: false
2021-05-08 14:20:43.329 T:1452    DEBUG <general>: Thread BackgroundLoader 2503631520 terminating
2021-05-08 14:20:44.905 T:1230    DEBUG <general>: CLibInputKeyboard::ProcessKey - using delay: 400ms repeat: 80ms
2021-05-08 14:20:44.906 T:1453    DEBUG <general>: Thread Timer start, auto delete: false
2021-05-08 14:20:44.907 T:1219    DEBUG <general>: Keyboard: scancode: 0x9e, sym: 0x00a6, unicode: 0x0000, modifier: 0x0
2021-05-08 14:20:45.033 T:1453    DEBUG <general>: Thread Timer 2520416928 terminating
2021-05-08 14:20:45.036 T:1219    DEBUG <general>: Keyboard: scancode: 0x9e, sym: 0x00a6, unicode: 0x0000, modifier: 0x0
2021-05-08 14:20:45.036 T:1219    DEBUG <general>: HandleKey: browser_back (0xf0b0) pressed, action is Back
'

I checked and rechecked my user:pass and they are correct. What could be the issue?

**Comment by minnixtx** [comment]
Ok I switched back to tvheadend 4.2 and am no longer having the authentication issue. I changed the title accordingly.

**Comment by wbeard52** [comment]
Updated version 2.1.1 to fix 4.3 authentication issues.
