### ISSUE TITLE
Unable to run addon itself

### ISSUE THREAD

**Issue by minnixtx** [edit4ever/script.module.zap2epg#51]
HW: Radxa Zero
OS: Coreelec 19.5-Matrix_rc1

I installed the addon via zip and following the setup info to run the addon first I did so and received this error:

```
2022-05-17 21:35:51.253 T:8847    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: function takes at most 2 arguments (4 given)
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.zap2epg/default.py", line 79, in <module>
                                                       check_status = check_load.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 943, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://127.0.0.1:9981/api/status/connections

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.zap2epg/default.py", line 81, in <module>
                                                       dialog.ok("Tvheadend Access Error!", str(err), "", "Please check your username/password in settings.")
                                                   TypeError: function takes at most 2 arguments (4 given)
                                                   -->End of Python script error report<--

2022-05-17 21:35:51.597 T:4025     INFO <general>: Loading skin file: DialogTextViewer.xml, load type: KEEP_IN_MEMORY
2022-05-17 21:35:51.809 T:8847     INFO <general>: Python interpreter stopped
2022-05-17 21:35:51.825 T:8846    ERROR <general>: GetDirectory - Error getting plugin://script.module.zap2epg/
```

So I went ahead and setup the tvheadend user and password next and try to rerun the addon and get this:

```
2022-05-17 21:48:14.293 T:10569   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: function takes at most 2 arguments (4 given)
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.zap2epg/default.py", line 79, in <module>
                                                       check_status = check_load.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 943, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://admin:<mypassword>@127.0.0.1:9981/api/status/connections

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.zap2epg/default.py", line 81, in <module>
                                                       dialog.ok("Tvheadend Access Error!", str(err), "", "Please check your username/password in settings.")
                                                   TypeError: function takes at most 2 arguments (4 given)
                                                   -->End of Python script error report<--

```

My username and password are correct and I can log in to TVHeadend just fine. TVHE both server and client are on the same machine. I am just unable to run the addon to set my parameters. Any advice please? Thanks

**Comment by minnixtx** [comment]
So there seems to be a conflict between zap2epg and ver 4.3 of TVHE, at least on my device. I installed TVHE 4.2 and this has resolved the issue. Since TVHE is still being maintained from the coreelec team, I'm going to mark this as closed.

**Comment by Phaelkyn** [comment]
I was getting the same issue with 4.3 on Manjaro and got around it. 
In the file the Kodi log mentions, default.py,  put a hash in front of line 79.
` #      check_status = check_load.raise_for_status()`
After that, the addon ran in Kodi. 

Even better, do this.
It is mentioned in a different closed issue to change a TVH setting. 
**Configuration/General/Base/Authentication Type:**  change drop down to **"both plain and digest"**
